### ISSUE TITLE
change docu

### ISSUE THREAD

**Issue by winne27** [Jean-PhilippeD/gladysv2-fhem#1]
Replace

2.You need to install FHEM.js from https://github.com/winne27/fhem.js/tree/master . It give you control with socket.io over you FHEM server

by
1. You need to install fhem.js by the following command:

npm install -g fhem.js

---

this is a suggenstion by winne27

**Comment by Jean-PhilippeD** [comment]
Hello,
You're right ! 
But right now I'm working on Gladys V3 and this module is deprecated.
